# Generated by Django 4.0.3 on 2023-04-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
