# Generated by Django 4.0.3 on 2023-04-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_appointment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='VIP',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
