# Generated by Django 4.0.3 on 2023-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_vip_alter_status_id_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=100),
        ),
    ]
