# Generated by Django 4.0.3 on 2023-04-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_automobilevo_import_href'),
        ('service_rest', '0006_alter_automobilevo_import_href'),
    ]

    operations = [
    ]
